# config.yml
server:
  port: 8023
  logsDirectory: "logs"

security:
  whitelistEnabled: false
  whitelistedIps:
    - "127.0.0.1"
    - "192.168.1.100"
    - "10.0.0.5"

websocket:
  enabled: true
  webRtcEnabled: true

blockedDomains:
  - "blocked-domain.com"
  - "malicious-site.org"
  - "192.168.1.200"

errorPage:
  title: "Access Denied"
  message: "This domain is blocked by proxy settings."